# Generated by Django 4.1.4 on 2022-12-12 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chamber", "0002_remove_case_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Case",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
